name: Docker Run Action Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upgrade runtime
        uses: ./
        with:
          mnemonic: 'asd asd asd qwe asd zxc asd qwe'
          rpc_url: 'wss://mychain.com'
          wasm_file: '/runtime.wasm'
      