name: Docker Run Action Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker action and set output for testing
        uses: ./
        id: run-docker
        with:
          image: debian
          run: |
            echo "::set-output name=docker-version::`echo $DOCKER_VERSION`"
      